<a href="https://colab.research.google.com/github/MateoProjects/UtilsAI/blob/main/numpy_Utils.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

A lot of functions that can be used for process data using numpy. 

## Importing numpy and print version



In [1]:
import numpy as np
print("Loaded", np.__version__)

Loaded 1.19.5


## Creating NumPy arrays

The basic ndarray is created using the **array** function, which takes any sequence as an input parameter. NumPy arrays can be easily created from lists 


In [ ]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array. Matrix 2x2
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)



var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


* We can define the types of elements. Numpy has a lot of types. See [Numpy Types](https://numpy.org/doc/stable/user/basics.types.html)

* Or we can create a new array using an other array created before and change their type. See **var4** and **var5**

In [ ]:
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=np.complex)
print("var5 =", var5)

## Array Properties
The important attributes of the ndarray are

*   shape: Dimensions of the array
*   size: Total number of elements in the array
*   ndim: Number of axes
*   dtype: Type of the elements of the array



In [ ]:
print(var1.dtype, '\t', var1.shape, '\t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t', var4.shape, '\t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t', var5.size, '\t', var5.ndim)

# Other array creation methods

It is not always necessary to have the elements defined during the creation of the arrays. There are several NumPy functions that allows to create arrays to act as placeholders before the actual computations.



We can create different array objects using the following functions: (1) zeros, (2) ones, (3) empty, (4) zeros_like, (5) ones_like, (6) empty_like 


In [2]:
# Solution
zeros = np.zeros(2)
ones = np.ones(3)
empty = np.empty(2) # random information
zeros_like = np.zeros_like(ones) # return array with same dimensions and shapes thant the entry parameter
ones_like = np.ones_like(ones)
empty_like = np.empty_like(ones)

Zeros initialitze with all components with zeros meanwhile empty create an array with random numbers. It's only for initialitze array with random values.



* We have a linspace function that between two given values x and y and a third integer parameter n, creates an array of n uniformaly distributed numbers between x and y.

In [3]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## Shape Manipulations

* **Arange functions** : are for generate array between two values (we can define the increment of array for exemple : np.arange(3,7,2) and this will show us this array [3,5] )
<br>
<br>
* **Reshape function** : distribute all components of the array ones, therefore the product of the size of the shape needs to be the number of components.
<br>
<br>
* **Resize function**: allows to increase or decrease array. If the size of dimensions are small than the original array n elements will be deleted. Meanwhile if size is bigger than original array resize will repeteat elements starting on the first element of array.

In [ ]:
# Creating a numpy array using arange function
var6 = np.arange(12, dtype=np.int)
print(var6)

# Reshaping the array into 2 x 5 array
var6 = var6.reshape(2,6)
print(var6)

# Reshaping the array in 3 dimensions
var6 = var6.reshape(3,2,2)
print(var6)

# Note that it is not always necessary to give all three dimensions
var6 = var6.reshape(1,2,-1)
print(var6)

var6 = np.resize(var6, (2,40))
print(var6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11
   0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3]
 [ 4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3
   4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7]]


## Indexing, Slicing and Iterating

Indexing and slicing is similar to python lists. We use the **[ ]** operator for providing slices and indices.

In [ ]:
var7 = np.array([1, 2, 3, 4, 5])

# indexing the second element
# Remember array indices start with 0 in numpy
print(var7[1])

# slicing the first two elements of the array
print(var7[0:2])

2
[1 2]


In [ ]:
# it is also possible to slice arrays based on a condition
print(var7[var7 % 2 == 0])  # prints all the even numbers in the array

[2 4]


In [ ]:
var8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(var8)

# indexing the element at second row and second column
print(var8[1,1])

# it is possible to slice the entire row or column
print(var8[1])
print(var8[:,1])

# slice a particular range
print(var8[0:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
5
[4 5 6]
[2 5 8]
[[1 2]
 [4 5]]


A visual illustration of slicing mechanism can be seen here

![numpy_indexing.png](https://drive.google.com/uc?export=view&id=1y6rrsrihu3QS5_NGdYMo9mBnbv0qHehq)

*Reference: http://scipy-lectures.org*


**nonzero function**: Returns a tuple of array (one for each dimension) that contains the positions with non zero values
...

In [ ]:
# solutio
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
print(np.nonzero(x))

[[3 0 0]
 [0 4 0]
 [5 6 0]]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))


In [ ]:
var9 = np.array([[1, 2, 3], [4, 5, 6]])

for i in var9: # outer loop to access row
    print(i) # returs the entire row

for i in var9: # outer loop to access row
    for j in i:  # iterating each element of the row
        print(j) # returs the element value

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
# an alternative to the nesting for loop is the nditer function
var10 = np.array([[1, 2, 3], [4, 5, 6]])
var10=np.resize(var10,(2,2,2))
for i in np.nditer(var10):
    print(i)

1
2
3
4
5
6
1
2


## Enumerate Array

**ndenumarte function**: return a list that contains for each position, the cordinates in numpy array and the value that contains.




In [5]:

a = np.array([[1, 2], [3, 4]])
for index, i in np.ndenumerate(a):
  print(index,i)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


This leaves us with the question of how the array copy works in numpy

# Array Copy

When we create a new array using the '=' operator, no new copy of the array is created, ie, only a name is created but it refers to the same object.

In [ ]:
var13 = np.array([1, 2, 3, 4, 5])

var14 = var13
print('Before modifying', var13)

var14[0] += 1
print('After modifying', var13)

Before modifying [1 2 3 4 5]
After modifying [2 2 3 4 5]


When a view function is used to create a copy of the array, or when the array is sliced, the returned array is only a shallow copy of the original array, ie, an array object is created but the object points to the same data

In [ ]:
var15 = np.array([1, 2, 3, 4, 5])

var16 = var15.view()
print('Before modifying (using view)', var15)

var16[0] += 1
print('After modifying (using view)', var15)

var17 = var15[0:3]
print('Before modifying (using slice)', var15)

var17[2] += 1
print('After modifying (using slice)', var15)

Before modifying (using view) [1 2 3 4 5]
After modifying (using view) [2 2 3 4 5]
Before modifying (using slice) [2 2 3 4 5]
After modifying (using slice) [2 2 4 4 5]


To create a deep copy of the array, it is necessary to use the copy method

In [ ]:
var18 = np.array([1, 2, 3, 4, 5])

var19 = var18.copy()
print('Before modifying (using copy)', var18)

var19[0] += 1
print('After modifying (using copy)', var18)

Before modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [1 2 3 4 5]


# Adding new axis

It is also possible to increase the dimensions of a numpy array. **np.newaxis** and **expand_dims** can be used to increase the dimensions of the array. This would be used very handy in building convolutional neural networks where you would need to have uniform channel lengths *(will be used in the later exercises)*.

In [ ]:
var20 = np.array([1, 2, 3, 4, 5])
print(var20.shape)

a = var20[np.newaxis, :]  # adding new axis to the first axis
print(a.shape)

b = a[np.newaxis, :]  # adding new axis to the first axis
print(b.shape)

c = np.expand_dims(var20, axis=1)  # adding new axis to the second axis
print(c.shape)

d = np.expand_dims(var20, axis=0)  # adding new axis to the first axis
print(d.shape)

(5,)
(1, 5)
(1, 1, 5)
(5, 1)
(1, 5)


# Broadcasting Rules

Broadcasting deals with how numpy treats arrays with different sizes during arithmetic operations. In general, the smaller arrays are broadcasted into the larger array shapes so that both the arrays are compatible.

Read [basic broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html) for basic knowledge about broadcasting.
Also read [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy).


In [ ]:
var20 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

print(var20)

print(var20 * 2)  # multiplying each element with 2

print(var20 + [1, 0, 1])  # adding each row with [1, 0, 1]]

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]
[[ 2.4  4.6  8. ]
 [ 2.4  6.8 10.4]
 [ 0.   2.   2.6]
 [ 0.   2.   0.4]]
[[2.2 2.3 5. ]
 [2.2 3.4 6.2]
 [1.  1.  2.3]
 [1.  1.  1.2]]


## Normalizing values 

Normalizing values is an important area in any image processing and machine learning problem. In this cell, we will try to apply normalization at different axis to understand the role of broadcasting.

In [ ]:
var21 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

# compute row wise mean
var21_mean =  var21.mean(1)             # code fill up
print(var21_mean)

# compute column wise mean
var21_mean_clm =  var21.mean(0)             # code fill up
print(var21_mean_clm)

# do row wise mean subtraction and column wise mean subtraction
# solution

var21_row = var21 - var21.mean(1, keepdims=True)
var21_col = var21 - var21.mean(0, keepdims=True)

print(var21_row)
print(var21_col)


# how do we normalize the entire array using the global mean?
# solution

var21_normalized = np.mean(var21)
var21_normalized


[2.5        3.26666667 0.76666667 0.4       ]
[0.6   1.925 2.675]
[[-1.3        -0.2         1.5       ]
 [-2.06666667  0.13333333  1.93333333]
 [-0.76666667  0.23333333  0.53333333]
 [-0.4         0.6        -0.2       ]]
[[ 0.6    0.375  1.325]
 [ 0.6    1.475  2.525]
 [-0.6   -0.925 -1.375]
 [-0.6   -0.925 -2.475]]


1.7333333333333332