<a href="https://colab.research.google.com/github/MateoProjects/UtilsAI/blob/main/numpy_Utils.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

A lot of functions that can be used for process data using numpy. 

## Importing numpy and print version



In [1]:
import numpy as np
print("Loaded", np.__version__)

Loaded 1.19.5


## Creating NumPy arrays

The basic ndarray is created using the **array** function, which takes any sequence as an input parameter. NumPy arrays can be easily created from lists 


In [ ]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array. Matrix 2x2
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)



var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


* We can define the types of elements. Numpy has a lot of types. See [Numpy Types](https://numpy.org/doc/stable/user/basics.types.html)

* Or we can create a new array using an other array created before and change their type. See **var4** and **var5**

In [ ]:
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=np.complex)
print("var5 =", var5)

## Array Properties
The important attributes of the ndarray are

*   shape: Dimensions of the array
*   size: Total number of elements in the array
*   ndim: Number of axes
*   dtype: Type of the elements of the array



In [ ]:
print(var1.dtype, '\t', var1.shape, '\t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t', var4.shape, '\t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t', var5.size, '\t', var5.ndim)

# Other array creation methods

It is not always necessary to have the elements defined during the creation of the arrays. There are several NumPy functions that allows to create arrays to act as placeholders before the actual computations.



We can create different array objects using the following functions: (1) zeros, (2) ones, (3) empty, (4) zeros_like, (5) ones_like, (6) empty_like 


In [2]:
# Solution
zeros = np.zeros(2)
ones = np.ones(3)
empty = np.empty(2) # random information
zeros_like = np.zeros_like(ones) # return array with same dimensions and shapes thant the entry parameter
ones_like = np.ones_like(ones)
empty_like = np.empty_like(ones)

Zeros initialitze with all components with zeros meanwhile empty create an array with random numbers. It's only for initialitze array with random values.



* We have a linspace function that between two given values x and y and a third integer parameter n, creates an array of n uniformaly distributed numbers between x and y.

In [3]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## Shape Manipulations

* **Arange functions** : are for generate array between two values (we can define the increment of array for exemple : np.arange(3,7,2) and this will show us this array [3,5] )

* **Reshape function** : distribute all components of the array ones, therefore the product of the size of the shape needs to be the number of components.

* **Resize function**: allows to increase or decrease array. If the size of dimensions are small than the original array n elements will be deleted. Meanwhile if size is bigger than original array resize will repeteat elements starting on the first element of array.

In [ ]:
# Creating a numpy array using arange function
var6 = np.arange(12, dtype=np.int)
print(var6)

# Reshaping the array into 2 x 5 array
var6 = var6.reshape(2,6)
print(var6)

# Reshaping the array in 3 dimensions
var6 = var6.reshape(3,2,2)
print(var6)

# Note that it is not always necessary to give all three dimensions
var6 = var6.reshape(1,2,-1)
print(var6)

var6 = np.resize(var6, (2,40))
print(var6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11
   0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3]
 [ 4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3
   4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7]]
